### ISSUE TITLE
getRolesForUserTestIT faile with 401 

### ISSUE THREAD

**Issue by richardchen3015** [blackducksoftware/hub-common#158]
getRolesForUserTestIT faile with 401
TRACE: starting request: https://blackduck.appsec.bns/api/users?offset=0&limit=100
TRACE: Request : Request{method=POST, url=https://blackduck.appsec.bns/j_spring_security_check, tag=null}
TRACE: Request does not have any headers.
TRACE: Response : Response{protocol=http/1.1, code=401, message=, url=https://blackduck.appsec.bns/j_spring_security_check}
TRACE: Response headers : 
TRACE: Header cache-control : no-cache, no-store, max-age=0, must-revalidate
TRACE: Header connection : keep-alive
TRACE: Header content-type : application/json;charset=UTF-8
TRACE: Header date : Mon, 12 Feb 2018 00:48:54 GMT
TRACE: Header expires : 0
TRACE: Header pragma : no-cache
TRACE: Header server : nginx/1.10.3
TRACE: Header set-cookie : JSESSIONID=2EAEDF4EDDD5BBD2B532DCB9706407E5; Path=/; secure; HttpOnly
TRACE: Header strict-transport-security : max-age=31536000; includeSubDomains
TRACE: Header transfer-encoding : chunked
TRACE: Header vary : Accept-Encoding
TRACE: Header x-content-type-options : nosniff
TRACE: Header x-csrf-header : X-CSRF-TOKEN
TRACE: Header x-csrf-param : _csrf
TRACE: Header x-csrf-token : bdc5842e-619f-43c8-8729-d5cdd0a14430
TRACE: Header x-xss-protection : 1; mode=block
TRACE: completed request: https://blackduck.appsec.bns/api/users?offset=0&limit=100 (496 ms)
com.blackducksoftware.integration.hub.rest.exception.IntegrationRestException: Connection Error: 401 
	at com.blackducksoftware.integration.hub.rest.CredentialsRestConnection.clientAuthenticate(CredentialsRestConnection.java:86)
	at com.blackducksoftware.integration.hub.rest.RestConnection.connect(RestConnection.java:122)
	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:383)
	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:345)
	at com.blackducksoftware.integration.hub.rest.RestConnection.createResponse(RestConnection.java:334)
	at com.blackducksoftware.integration.hub.request.HubRequest.executeGet(HubRequest.java:62)
	at com.blackducksoftware.integration.hub.service.AllHubViewsTransformer.getAllViews(AllHubViewsTransformer.java:121)
	at com.blackducksoftware.integration.hub.service.AllHubViewsTransformer.getAllViewsFromApi(AllHubViewsTransformer.java:75)
	at com.blackducksoftware.integration.hub.service.AllHubViewsTransformer.getAllViewsFromApi(AllHubViewsTransformer.java:62)
	at com.blackducksoftware.integration.hub.service.HubService.getAllViewsFromApi(HubService.java:198)
	at com.blackducksoftware.integration.hub.api.user.UserService.getAllUsers(UserService.java:45)
	at com.blackducksoftware.integration.hub.api.user.UserService.getUserByUserName(UserService.java:50)
	at com.blackducksoftware.integration.hub.dataservice.user.UserDataService.getRolesForUser(UserDataService.java:70)
	at com.bns.appsec.integration.UserProject.main(UserProject.java:29)

**Comment by ekerwin** [comment]
We're going to need a little more detail here.

In the current release of hub-common, you would be using com.blackducksoftware.integration.hub.service.UserGroupService, which has a method:
public List<RoleAssignmentView> getRolesForUser(final String userName) throws IntegrationException

This method works against a 4.4.0 Hub server.

Can you provide some more detail as to what you're looking for?
